package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"github.com/MorhafAlshibly/coanda/services/bff/graph"
	"github.com/MorhafAlshibly/coanda/services/bff/model"
)

// CreateItem used to create a new item
func (r *mutationResolver) CreateItem(ctx context.Context, input model.CreateItem) (*model.Item, error) {
	return r.ItemService.Create(ctx, input)
}

// Item used to get a single item
func (r *queryResolver) Item(ctx context.Context, input model.GetItem) (*model.Item, error) {
	return r.ItemService.Get(ctx, input)
}

// Items used to get all items
func (r *queryResolver) Items(ctx context.Context, input model.GetItems) ([]*model.Item, error) {
	return r.ItemService.GetAll(ctx, input)
}

func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
