// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package model

import (
	"encoding/json"
	"time"
)

type RankedTeam struct {
	Name      string
	Owner     uint64
	Score     int64
	Ranking   uint64
	Data      json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Team struct {
	Name      string
	Owner     uint64
	Score     int64
	Data      json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TeamMember struct {
	Team      string
	UserID    uint64
	Data      json.RawMessage
	JoinedAt  time.Time
	UpdatedAt time.Time
}

type TeamOwner struct {
	Team   string
	UserID uint64
}
