// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package model

import (
	"encoding/json"
	"time"
)

type LastTeamMember struct {
	Team            string `db:"team"`
	MaxMemberNumber uint32 `db:"max_member_number"`
}

type RankedTeam struct {
	Name      string          `db:"name"`
	Owner     uint64          `db:"owner"`
	Score     int64           `db:"score"`
	Ranking   uint64          `db:"ranking"`
	Data      json.RawMessage `db:"data"`
	CreatedAt time.Time       `db:"created_at"`
	UpdatedAt time.Time       `db:"updated_at"`
}

type Team struct {
	Name      string          `db:"name"`
	Owner     uint64          `db:"owner"`
	Score     int64           `db:"score"`
	Data      json.RawMessage `db:"data"`
	CreatedAt time.Time       `db:"created_at"`
	UpdatedAt time.Time       `db:"updated_at"`
}

type TeamMember struct {
	Team         string          `db:"team"`
	UserID       uint64          `db:"user_id"`
	MemberNumber uint32          `db:"member_number"`
	Data         json.RawMessage `db:"data"`
	JoinedAt     time.Time       `db:"joined_at"`
	UpdatedAt    time.Time       `db:"updated_at"`
}

type TeamOwner struct {
	Team   string `db:"team"`
	UserID uint64 `db:"user_id"`
}
