CREATE TABLE team (
    name VARCHAR(255) PRIMARY KEY NOT NULL,
    owner BIGINT UNSIGNED UNIQUE NOT NULL,
    score BIGINT NOT NULL DEFAULT 0,
    data JSON NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX score_idx (score DESC)
) ENGINE = InnoDB;
CREATE VIEW ranked_team AS
SELECT name,
    owner,
    score,
    DENSE_RANK() OVER (
        ORDER BY score DESC
    ) AS ranking,
    data,
    created_at,
    updated_at
FROM team
ORDER BY score DESC;
CREATE TABLE team_member (
    team VARCHAR(255) NOT NULL,
    user_id BIGINT UNSIGNED PRIMARY KEY NOT NULL,
    data JSON NOT NULL,
    joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (team) REFERENCES team(name) ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX fk_team_idx (team ASC)
) ENGINE = InnoDB;
CREATE TABLE team_owner (
    team VARCHAR(255) PRIMARY KEY NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (team) REFERENCES team(name) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (user_id) REFERENCES team_member(user_id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = InnoDB;