sources:
   - name: Item
     handler:
        grpc:
           endpoint: localhost:50051
           source: api/item.proto
   - name: Team
     handler:
        grpc:
           endpoint: localhost:50052
           source: api/team.proto
   - name: Record
     handler:
        grpc:
           endpoint: localhost:50053
           source: api/record.proto
transforms:
   - filterSchema:
        filters:
           - Query.!api_TeamService_{connectivityState}
           - Query.!api_ItemService_{connectivityState}
           - Query.!api_RecordService_{connectivityState}
   - rename:
        renames:
           - from:
                type: Query
                field: api_(.*)_(.*)
             to:
                type: Query
                field: $2
             useRegExpForFields: true
   - rename:
        renames:
           - from:
                type: Mutation
                field: api_(.*)_(.*)
             to:
                type: Mutation
                field: $2
             useRegExpForFields: true
