
version: '3.9'

services:

  general:
    env_file: .env
    build:
      context: .
      args:
        RUN_PATH: "build/src/microservices/general/index.js"
    ports:
      - "5050:5050"

  replays:
    env_file: .env
    build:
      context: .
      args:
        RUN_PATH: "build/src/microservices/replays/index.js"
    ports:
      - "5055:5055"

