services:
   bff:
      build:
         context: ./
         dockerfile: ./cmd/bff/Dockerfile
      image: ${DOCKER_IMAGE_URL}/bff
      container_name: bff
      ports:
         - "${DOCKER_BFF_PORT}:${BFF_PORT}"
   item:
      build:
         context: ./
         dockerfile: ./cmd/item/Dockerfile
      image: ${DOCKER_IMAGE_URL}/item
      container_name: item
      ports:
         - "${DOCKER_ITEM_PORT}:${ITEM_PORT}"
         - "${DOCKER_ITEM_METRICSPORT}:${ITEM_METRICSPORT}"
   team:
      build:
         context: ./
         dockerfile: ./cmd/team/Dockerfile
      image: ${DOCKER_IMAGE_URL}/team
      container_name: team
      ports:
         - "${DOCKER_TEAM_PORT}:${TEAM_PORT}"
         - "${DOCKER_TEAM_METRICSPORT}:${TEAM_METRICSPORT}"
   record:
      build:
         context: ./
         dockerfile: ./cmd/record/Dockerfile
      image: ${DOCKER_IMAGE_URL}/record
      container_name: record
      ports:
         - "${DOCKER_RECORD_PORT}:${RECORD_PORT}"
         - "${DOCKER_RECORD_METRICSPORT}:${RECORD_METRICSPORT}"
   redis:
      image: "redis:alpine"
      container_name: redis
      ports:
         - "${DOCKER_REDIS_PORT}:6379"
