version: "3"

includes:
   bff:
      taskfile: ./src/bff/BFF.yml
      dir: ./src/bff
   tournaments:
      taskfile: ./src/microservices/tournaments/Tournaments.yml
      dir: ./src/microservices/tournaments
   infrastructure:
      taskfile: ./infrastructure/Infrastructure.yml
      dir: ./infrastructure
   docs:
      taskfile: ./docs/Docs.yml
      dir: ./docs
