version: "3"

includes:
   bff:
      taskfile: cmd/bff/Bff.yml
      dir: cmd/bff
   team:
      taskfile: cmd/team/Team.yml
      dir: cmd/team

tasks:
   generate:
      dir: ./api
      cmds:
         - protoc -I . --go_out=./ --go-grpc_out=./ --graphql_out=./ *.proto
