version: "3"

includes:
   bff:
      taskfile: cmd/bff/Bff.yml
      dir: cmd/bff
   item:
      taskfile: cmd/item/Item.yml
      dir: cmd/item
   team:
      taskfile: cmd/team/Team.yml
      dir: cmd/team
   record:
      taskfile: cmd/record/Record.yml
      dir: cmd/record
   tournament:
      taskfile: cmd/tournament/Tournament.yml
      dir: cmd/tournament
   # azure:
   #    taskfile: infrastructure/azure/Azure.yml
   #    dir: infrastructure/azure
   # oci:
   #    taskfile: infrastructure/oci/Oci.yml
   #    dir: infrastructure/oci

tasks:
   generate:
      dir: ./api
      cmds:
         - task: sqlc
         - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative *.proto
         - task: bff:generate
   migrate:
      dotenv: ["./env/.env.{{.ENV}}"]
      cmds:
         - atlas schema apply --to "file://migration" -u ${MYSQL_CONN} --dev-url "docker://mysql/8/dev"
      requires:
         vars: [ENV]
   sqlc:
      cmds:
         - sqlc generate
   install-proto:
      cmds:
         - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
         - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
