AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:
   goFunction:
      Type: AWS::Serverless::Function
      Properties:
         Handler: main
         Runtime: go1.x
         Events:
            ScheduledEvent:
               Type: Schedule
               Properties:
                  Schedule: cron(0 0 * * ? *) # Run every day at midnight
