// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package model

import (
	"encoding/json"
	"time"
)

type RankedRecord struct {
	ID        uint64          `db:"id"`
	Name      string          `db:"name"`
	UserID    uint64          `db:"user_id"`
	Record    uint64          `db:"record"`
	Ranking   uint64          `db:"ranking"`
	Data      json.RawMessage `db:"data"`
	CreatedAt time.Time       `db:"created_at"`
	UpdatedAt time.Time       `db:"updated_at"`
}

type Record struct {
	ID        uint64          `db:"id"`
	Name      string          `db:"name"`
	UserID    uint64          `db:"user_id"`
	Record    uint64          `db:"record"`
	Data      json.RawMessage `db:"data"`
	CreatedAt time.Time       `db:"created_at"`
	UpdatedAt time.Time       `db:"updated_at"`
}
