package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/MorhafAlshibly/coanda/api"
)

// Webhook is the resolver for the Webhook field.
func (r *mutationResolver) Webhook(ctx context.Context, input *api.WebhookRequest) (*api.WebhookResponse, error) {
	return r.webhookClient.Webhook(ctx, input)
}
