// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package model

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Item struct {
	ID        string
	Type      string
	Data      json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt sql.NullTime
}
