// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: queries.sql

package model

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createItem = `-- name: CreateItem :execresult
INSERT INTO item (
        id,
        type,
        data,
        expires_at
    )
VALUES (?, ?, ?, ?)
`

type CreateItemParams struct {
	ID        string
	Type      string
	Data      json.RawMessage
	ExpiresAt sql.NullTime
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createItem,
		arg.ID,
		arg.Type,
		arg.Data,
		arg.ExpiresAt,
	)
}

const deleteItem = `-- name: DeleteItem :execresult
DELETE FROM item
WHERE id = ?
    AND type = ?
LIMIT 1
`

type DeleteItemParams struct {
	ID   string
	Type string
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteItem, arg.ID, arg.Type)
}

const getItem = `-- name: GetItem :one
SELECT id,
    type,
    data,
    created_at,
    updated_at,
    expires_at
FROM item
WHERE id = ?
    AND type = ?
LIMIT 1
`

type GetItemParams struct {
	ID   string
	Type string
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, arg.ID, arg.Type)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Data,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getItems = `-- name: GetItems :many
SELECT id,
    type,
    data,
    created_at,
    updated_at,
    expires_at
FROM item
WHERE type = ?
ORDER BY id ASC
LIMIT ? OFFSET ?
`

type GetItemsParams struct {
	Type   sql.NullString
	Limit  int32
	Offset int32
}

func (q *Queries) GetItems(ctx context.Context, arg GetItemsParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getItems, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :execresult
UPDATE item
SET data = CASE
        WHEN CAST(? as unsigned) != 0 THEN ?
        ELSE data
    END,
    expires_at = CASE
        WHEN ? IS NOT NULL THEN ?
        ELSE expires_at
    END
WHERE id = ?
    AND type = ?
LIMIT 1
`

type UpdateItemParams struct {
	DataExists int64
	Data       json.RawMessage
	ExpiresAt  sql.NullTime
	ID         string
	Type       string
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateItem,
		arg.DataExists,
		arg.Data,
		arg.ExpiresAt,
		arg.ExpiresAt,
		arg.ID,
		arg.Type,
	)
}
