// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package model

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const GetEndedEventRoundLeaderboard = `-- name: GetEndedEventRoundLeaderboard :many
SELECT erl.id,
    erl.event_id,
    erl.round_name,
    erl.event_user_id,
    erl.event_round_id,
    erl.result,
    erl.score,
    erl.ranking,
    erl.data,
    erl.created_at,
    erl.updated_at
FROM event_round_leaderboard erl
    JOIN event_round er ON erl.event_round_id = er.id
WHERE erl.event_round_id = ?
    AND er.ended_at < NOW()
    AND (
        er.sent_to_third_party_at IS NULL
        OR er.sent_to_third_party_at > NOW()
    )
ORDER BY erl.ranking ASC
LIMIT ?
`

type GetEndedEventRoundLeaderboardParams struct {
	EventRoundID uint64 `db:"event_round_id"`
	Limit        int32  `db:"limit"`
}

func (q *Queries) GetEndedEventRoundLeaderboard(ctx context.Context, arg GetEndedEventRoundLeaderboardParams) ([]EventRoundLeaderboard, error) {
	rows, err := q.db.QueryContext(ctx, GetEndedEventRoundLeaderboard, arg.EventRoundID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventRoundLeaderboard
	for rows.Next() {
		var i EventRoundLeaderboard
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.RoundName,
			&i.EventUserID,
			&i.EventRoundID,
			&i.Result,
			&i.Score,
			&i.Ranking,
			&i.Data,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetEndedEventRounds = `-- name: GetEndedEventRounds :many
SELECt id,
    event_id,
    name,
    scoring,
    data,
    ended_at,
    created_at,
    updated_at
FROM event_round
WHERE ended_at < NOW()
    AND (
        sent_to_third_party_at IS NULL
        OR sent_to_third_party_at > NOW()
    )
ORDER BY id ASC
LIMIT ? OFFSET ?
`

type GetEndedEventRoundsParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

type GetEndedEventRoundsRow struct {
	ID        uint64          `db:"id"`
	EventID   uint64          `db:"event_id"`
	Name      string          `db:"name"`
	Scoring   json.RawMessage `db:"scoring"`
	Data      json.RawMessage `db:"data"`
	EndedAt   time.Time       `db:"ended_at"`
	CreatedAt time.Time       `db:"created_at"`
	UpdatedAt time.Time       `db:"updated_at"`
}

func (q *Queries) GetEndedEventRounds(ctx context.Context, arg GetEndedEventRoundsParams) ([]GetEndedEventRoundsRow, error) {
	rows, err := q.db.QueryContext(ctx, GetEndedEventRounds, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEndedEventRoundsRow
	for rows.Next() {
		var i GetEndedEventRoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Scoring,
			&i.Data,
			&i.EndedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateEventRoundSentToThirdParty = `-- name: UpdateEventRoundSentToThirdParty :execresult
UPDATE event_round
SET sent_to_third_party_at = NOW()
WHERE id = ?
    AND ended_at < NOW()
    AND (
        sent_to_third_party_at IS NULL
        OR sent_to_third_party_at > NOW()
    )
LIMIT 1
`

func (q *Queries) UpdateEventRoundSentToThirdParty(ctx context.Context, id uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, UpdateEventRoundSentToThirdParty, id)
}
