version: "3"

tasks:
   init:
      dotenv: ["backend.conf"]
      cmds:
         - az group create --name $RESOURCE_GROUP_NAME --location eastus
         - az storage account create --resource-group $RESOURCE_GROUP_NAME --name $STORAGE_ACCOUNT_NAME --sku Standard_LRS --encryption-services blob
         - az storage container create --name $CONTAINER_NAME --account-name $STORAGE_ACCOUNT_NAME
         - ACCOUNT_KEY=$(az storage account keys list --resource-group $RESOURCE_GROUP_NAME --account-name $STORAGE_ACCOUNT_NAME --query '[0].value' -o tsv)
         - terraform init -backend-config=backend.conf
   plan:
      cmds:
         - terraform plan
   apply:
      cmds:
         - terraform apply -auto-approve
