// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: queries.sql

package model

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const CreateTournament = `-- name: CreateTournament :execresult
INSERT INTO tournament (
        name,
        tournament_interval,
        user_id,
        score,
        data,
        tournament_started_at
    )
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateTournamentParams struct {
	Name                string                       `db:"name"`
	TournamentInterval  TournamentTournamentInterval `db:"tournament_interval"`
	UserID              uint64                       `db:"user_id"`
	Score               int64                        `db:"score"`
	Data                json.RawMessage              `db:"data"`
	TournamentStartedAt time.Time                    `db:"tournament_started_at"`
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, CreateTournament,
		arg.Name,
		arg.TournamentInterval,
		arg.UserID,
		arg.Score,
		arg.Data,
		arg.TournamentStartedAt,
	)
}