// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"database/sql"
	"encoding/json"
)

type Item struct {
	ID        string
	Data      json.RawMessage
	CreatedAt sql.NullTime
	ExpiresAt sql.NullTime
}

type RankedRecord struct {
	Name      string
	UserID    uint64
	Record    uint64
	Data      json.RawMessage
	Ranking   interface{}
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type RankedTeam struct {
	Name      string
	Owner     uint64
	Members   sql.NullString
	Score     int64
	Data      json.RawMessage
	Ranking   interface{}
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type RankedTeamMember struct {
	Name      string
	Owner     uint64
	Member    uint64
	Score     int64
	Data      json.RawMessage
	Ranking   interface{}
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Record struct {
	Name      string
	UserID    uint64
	Record    uint64
	Data      json.RawMessage
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Team struct {
	Name      string
	Owner     uint64
	Score     int64
	Data      json.RawMessage
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type TeamMember struct {
	TeamName string
	UserID   uint64
}
