openapi: 3.1.0
info:
  title: Coanda
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey
  schemas:
    CreateReplayInput:
      type: object
      required:
        - data
      properties:
        data:
          type: object
        expireAt:
          oneOf:
            - type: number
            - type: string
          description: Timestamp in ms
          default: 9999999999999
    GetReplayInput:
      type: object
      required:
        - _id
      properties:
        _id:
          type: string
          description: _id of the replay
    GetReplayIssue:
      oneOf:
        - const: replay_not_found
          type: string
          description: Replay data not found
  responses:
    CreateReplaySuccess:
      description: Success.
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                const: success
              data:
                type: string
                description: _id of the replay
    GetReplaySuccess:
      description: Success.
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                const: success
              data:
                type: object
                description: The data of the replay
    GetReplayFail:
      description: There is an issue with the request.
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                const: fail
              data:
                $ref: "#/components/schemas/GetReplayIssue"
    Invalid:
      description: Invalid input data.
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                const: invalid
              data:
                type: array
                items:
                  type: object
                  description: ZodIssue
    Error:
      description: Temporary server error.
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
                const: error
              data:
                type: string
                description: Error message
servers:
  - url: https://{tenant}
    variables:
      tenant:
        default: api.example.com
        description: The server host
paths:
  /ping:
    get:
      tags:
        - General
      operationId: ping
      summary: Ping the API
      description: Responds if the app is up and running
      responses:
        "200":
          description: App is up and running
      security:
        - ApiKeyAuth: []
  /replay:
    post:
      tags:
        - Replay
      summary: Create a replay
      operationId: createReplay
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateReplayInput"
      responses:
        "200":
          $ref: "#/components/responses/CreateReplaySuccess"
        "400":
          $ref: "#/components/responses/Invalid"
        "500":
          $ref: "#/components/responses/Error"
      security:
        - ApiKeyAuth: []
    get:
      tags:
        - Replay
      summary: Get a replay
      operationId: getReplay
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetReplayInput"
      responses:
        "200":
          $ref: "#/components/responses/GetReplaySuccess"
        "400":
          $ref: "#/components/responses/Invalid"
        "404":
          $ref: "#/components/responses/GetReplayFail"
        "500":
          $ref: "#/components/responses/Error"
      security:
        - ApiKeyAuth: []
tags: []
