// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package model

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const CreateTicket = `-- name: CreateTicket :execresult
INSERT INTO matchmaking_ticket (data, elo_window, expires_at)
VALUES (?, ?, ?)
`

type CreateTicketParams struct {
	Data      json.RawMessage `db:"data"`
	EloWindow uint32          `db:"elo_window"`
	ExpiresAt time.Time       `db:"expires_at"`
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, CreateTicket, arg.Data, arg.EloWindow, arg.ExpiresAt)
}
