name: Create documentation

on:
   push:
      branches: ["main"]
   workflow_dispatch:

permissions:
   contents: read
   pages: write
   id-token: write

concurrency:
   group: "pages"
   cancel-in-progress: true

jobs:
   Create_Documentation:
      environment:
         name: github-pages
         url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      name: Create Documentation
      steps:
         - name: Checkout
           uses: actions/checkout@v4

         - name: Generate docs
           run: |
              cd docs
              npm install
              npm run build
         - name: Setup Pages
           uses: actions/configure-pages@v5
         - name: Upload HTML
           uses: actions/upload-pages-artifact@v3
           with:
              path: "./docs/build"
         - name: Deploy to GitHub Pages
           id: deployment
           uses: actions/deploy-pages@v4
